import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from "pdf-lib";
import type { ReportContent } from "./report-template.js";

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 50;
const LINE_HEIGHT = 14;

type LayoutContext = {
  doc: PDFDocument;
  page: PDFPage;
  font: PDFFont;
  bold: PDFFont;
  y: number;
};

function wrapText(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(next, size) <= maxWidth) {
      current = next;
    } else {
      if (current) lines.push(current);
      current = word;
    }
  }
  if (current) lines.push(current);
  return lines.length > 0 ? lines : [""];
}

function ensureSpace(ctx: LayoutContext, needed: number): LayoutContext {
  if (ctx.y - needed >= MARGIN) return ctx;

  const page = ctx.doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  return { ...ctx, page, y: PAGE_HEIGHT - MARGIN };
}

function drawLines(
  ctx: LayoutContext,
  lines: string[],
  options: { size?: number; bold?: boolean; color?: ReturnType<typeof rgb> } = {},
): LayoutContext {
  const size = options.size ?? 11;
  const font = options.bold ? ctx.bold : ctx.font;
  const color = options.color ?? rgb(0.07, 0.07, 0.07);
  let next = ctx;

  for (const line of lines) {
    next = ensureSpace(next, LINE_HEIGHT + 4);
    next.page.drawText(line, {
      x: MARGIN,
      y: next.y,
      size,
      font,
      color,
    });
    next = { ...next, y: next.y - LINE_HEIGHT - 2 };
  }

  return next;
}

function drawSectionTitle(ctx: LayoutContext, title: string): LayoutContext {
  let next = ensureSpace(ctx, LINE_HEIGHT * 2);
  next = drawLines(next, [title], { size: 14, bold: true, color: rgb(0.05, 0.58, 0.53) });
  return { ...next, y: next.y - 6 };
}

function drawParagraph(ctx: LayoutContext, text: string, size = 11): LayoutContext {
  const maxWidth = PAGE_WIDTH - MARGIN * 2;
  const lines = wrapText(text, ctx.font, size, maxWidth);
  return drawLines(ctx, lines, { size });
}

export async function generateReportPdf(content: ReportContent): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let ctx: LayoutContext = {
    doc,
    page: doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]),
    font,
    bold,
    y: PAGE_HEIGHT - MARGIN,
  };

  ctx = drawLines(ctx, [content.auditTitle], { size: 20, bold: true });
  ctx = drawLines(ctx, [`Client: ${content.clientName}`], { size: 12 });
  ctx = drawLines(ctx, [`Generated: ${content.generatedAt}`], { size: 10, color: rgb(0.4, 0.4, 0.4) });
  ctx = { ...ctx, y: ctx.y - 12 };

  ctx = drawSectionTitle(ctx, "Executive Summary");
  ctx = drawParagraph(
    ctx,
    `Audit status: ${content.auditStatus}. Total spend: $${content.spendTotal.toLocaleString()}. ` +
      `Identified savings opportunity: $${content.savingsTotal.toLocaleString()} (${content.savingsPercent}% of spend).`,
  );
  ctx = { ...ctx, y: ctx.y - 8 };

  ctx = drawSectionTitle(ctx, "License Inventory");
  if (content.inventory.length === 0) {
    ctx = drawParagraph(ctx, "No license snapshot data imported for this audit.");
  } else {
    for (const row of content.inventory) {
      ctx = drawParagraph(
        ctx,
        `${row.sku} — qty ${row.quantity}, assigned ${row.assigned}, $${row.costMonthly.toLocaleString()}/mo`,
        10,
      );
    }
  }
  ctx = { ...ctx, y: ctx.y - 8 };

  ctx = drawSectionTitle(ctx, "Findings");
  if (content.findings.length === 0) {
    ctx = drawParagraph(ctx, "No findings recorded.");
  } else {
    for (const finding of content.findings) {
      ctx = drawParagraph(
        ctx,
        `[${finding.severity.toUpperCase()}] ${finding.title} — est. savings $${(finding.savingsEstimate ?? 0).toLocaleString()}`,
        10,
      );
      if (finding.description) {
        ctx = drawParagraph(ctx, finding.description, 9);
      }
    }
  }
  ctx = { ...ctx, y: ctx.y - 8 };

  ctx = drawSectionTitle(ctx, "Recommendations");
  if (content.recommendations.length === 0) {
    ctx = drawParagraph(ctx, "No recommendations generated.");
  } else {
    for (const rec of content.recommendations) {
      ctx = drawParagraph(
        ctx,
        `${rec.priority}. ${rec.action} (${rec.status})`,
        10,
      );
    }
  }

  ctx = { ...ctx, y: ctx.y - 16 };
  ctx = drawParagraph(
    ctx,
    "Generated by Vortex Optimizer — vendor-neutral Microsoft licensing advisory. Not a license reseller.",
    9,
  );

  return doc.save();
}
