import type { AuditDto } from "@vorzop/shared";

export type ReportFinding = {
  title: string;
  description: string | null;
  severity: string;
  savingsEstimate: number | null;
};

export type ReportRecommendation = {
  action: string;
  status: string;
  priority: number;
};

export type ReportInventoryRow = {
  sku: string;
  quantity: number;
  assigned: number;
  costMonthly: number;
};

export type ReportContent = {
  auditTitle: string;
  clientName: string;
  auditStatus: string;
  generatedAt: string;
  spendTotal: number;
  savingsTotal: number;
  savingsPercent: number;
  inventory: ReportInventoryRow[];
  findings: ReportFinding[];
  recommendations: ReportRecommendation[];
};

export function buildReportContent(
  audit: AuditDto,
  clientName: string,
  inventory: ReportInventoryRow[],
  findings: ReportFinding[],
  recommendations: ReportRecommendation[],
): ReportContent {
  const spendTotal = audit.spendTotal ?? 0;
  const savingsTotal =
    audit.savingsEstimate ??
    findings.reduce((sum, f) => sum + (f.savingsEstimate ?? 0), 0);
  const savingsPercent = spendTotal > 0 ? Math.round((savingsTotal / spendTotal) * 100) : 0;

  return {
    auditTitle: audit.title,
    clientName,
    auditStatus: audit.status,
    generatedAt: new Date().toISOString().slice(0, 10),
    spendTotal,
    savingsTotal,
    savingsPercent,
    inventory,
    findings,
    recommendations,
  };
}

export function generateReportHtml(content: ReportContent): string {
  const inventoryRows = content.inventory
    .map(
      (row) =>
        `<tr><td>${escapeHtml(row.sku)}</td><td>${row.quantity}</td><td>${row.assigned}</td><td>$${row.costMonthly.toLocaleString()}</td></tr>`,
    )
    .join("");

  const findingRows = content.findings
    .map(
      (f) =>
        `<tr><td>${escapeHtml(f.severity)}</td><td>${escapeHtml(f.title)}</td><td>$${(f.savingsEstimate ?? 0).toLocaleString()}</td></tr>`,
    )
    .join("");

  const recommendationRows = content.recommendations
    .map(
      (r) =>
        `<tr><td>${r.priority}</td><td>${escapeHtml(r.action)}</td><td>${escapeHtml(r.status)}</td></tr>`,
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(content.auditTitle)} — Vortex Optimizer Report</title>
  <style>
    body { font-family: system-ui, sans-serif; margin: 2rem; color: #111; }
    h1 { color: #0D9488; margin-bottom: 0.25rem; }
    h2 { color: #0D9488; margin-top: 2rem; border-bottom: 1px solid #e5e7eb; padding-bottom: 0.25rem; }
    table { border-collapse: collapse; width: 100%; margin-top: 0.75rem; }
    th, td { border: 1px solid #e5e7eb; padding: 0.5rem 0.75rem; text-align: left; font-size: 0.9rem; }
    th { background: #f9fafb; }
    .kpi { font-size: 1.5rem; font-weight: 600; }
    .meta { color: #6b7280; font-size: 0.875rem; }
  </style>
</head>
<body>
  <h1>${escapeHtml(content.auditTitle)}</h1>
  <p class="meta">Client: ${escapeHtml(content.clientName)} · Status: ${escapeHtml(content.auditStatus)} · Generated: ${content.generatedAt}</p>
  <h2>Executive Summary</h2>
  <p class="kpi">Identified savings: $${content.savingsTotal.toLocaleString()} (${content.savingsPercent}% of $${content.spendTotal.toLocaleString()} spend)</p>
  <h2>License Inventory</h2>
  <table>
    <thead><tr><th>SKU</th><th>Qty</th><th>Assigned</th><th>Monthly cost</th></tr></thead>
    <tbody>${inventoryRows || "<tr><td colspan=\"4\">No inventory data</td></tr>"}</tbody>
  </table>
  <h2>Findings</h2>
  <table>
    <thead><tr><th>Severity</th><th>Finding</th><th>Est. savings</th></tr></thead>
    <tbody>${findingRows || "<tr><td colspan=\"3\">No findings yet</td></tr>"}</tbody>
  </table>
  <h2>Recommendations</h2>
  <table>
    <thead><tr><th>Priority</th><th>Action</th><th>Status</th></tr></thead>
    <tbody>${recommendationRows || "<tr><td colspan=\"3\">No recommendations yet</td></tr>"}</tbody>
  </table>
  <footer><p>Generated by Vortex Optimizer — vendor-neutral Microsoft licensing advisory</p></footer>
</body>
</html>`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
